### ISSUE TITLE
Add support for alternative analysis views

### ISSUE THREAD

**Issue by dgzlopes** [grafana/k6-cloud-feature-requests#16]
I like the current analysis view, it works very well for load testing. 

But if I'm doing something that it's not load testing (k6 is very powerful and flexible :))... this view isn't very useful.

This feature request is about adding alternative views for the analysis tool. Those views can be curated by the k6 team for different use cases, and I can switch between them if needed.

Even if this can be done "automatically", for example, if some test has some qualities, I would prefer to have the option to switch between them manually, to gather insights from different perspectives.

(from my POV having these "curated" views is enough. Clearly letting the users create their own in more powerful, but that's another different discussion/request)

**Comment by robingustafsson** [comment]
This spans two features we plan to implement at some point:

* Support for saving result page config as a template to be used for other test runs, with possibility of setting a default template per test, and perhaps per project
* Support for displaying results of different types of tests: functional, monitoring etc.

We have looked into before, and will likely evaluate again, whether embedding Grafana to some extent would be a good path forward as we'd basically start implementing a lot of the features of Grafana in the cloud otherwise 😄

The upcoming Grafana data source plugin and PromQL like metrics API will be test beds for this to some degree.

**Comment by adshead** [comment]
It would be great if the current Trend chart on the dashboard allowed you to see the trend for an individually tagged test rather that the aggregated view of all tests that it currently offers. I'd also like to be able to specify which of the in-built metrics thet chart should use as opposed to just showing the 95th percentile.  For example, I'd like to see the **median** response time trend for a single http test over the course of many test runs.
