### ISSUE TITLE
Ability to add tags for each test run

### ISSUE THREAD

**Issue by robingustafsson** [grafana/k6-cloud-feature-requests#2]
_This is an idea submitted to our previous ideas portal_

> Would be great to add different tags on each run. Now we use the note-field to fill in our different changes for each, but it is hard to get an overview of the different settings used. Some tests we enable a feature and on some we disable it etc. Tags would help.

**Comment by na--** [comment]
Instead of simply having tags as UI fields in the web app, we probably should integrate this with the [`tags` k6 option](https://k6.io/docs/using-k6/options/#tags)? Both showing `key=value` in the web app when the user launches `k6 cloud --tag key=value script.js`, but also allowing them to specify them equivalently when starting test directly from the web app. 

https://github.com/k6io/cloud-feature-requests/issues/9 is somewhat connected, visualizing and specifying env vars from the web apps will be just as useful.

**Comment by robingustafsson** [comment]
Agree that having the ability to use tags for filtering tests and test runs on the dashboard and on the test overview page would be very handy in the web app. Not sure if we could somehow re-use `k6 run/cloud --tag` for this purpose on the test/test run level or if we need to introduce a separate option for `k6 cloud` and `k6 run --cloud`, something like a `--test-tag` or similar.

**Comment by na--** [comment]
We should be able to reuse them, `tags` are included in the .tar bundle.

**Comment by dgzlopes** [comment]
Also, I know that @mostafa has plans for static test-wide labels on Cloud APM (example: tagging all the metrics with env:staging).

If we can re-use the tags set by this feature, would be kinda cool.

**Comment by robingustafsson** [comment]
It feels like this is also overlapping into the feature of supporting environment variables so we should probably discuss how these things can work in unity.

**Comment by na--** [comment]
```bash
k6 archive --tag key=value --tag foo=bar 'github.com/loadimpact/k6/samples/http_get.js' 
tar xfO archive.tar metadata.json | jq '.options.tags'
```
results in
```
{
  "foo": "bar",
  "key": "value"
}
```

**Comment by markjmeier** [comment]
This issue has been moved to Grafana Feature requests
