### ISSUE TITLE
Botton to copy the url  in test results under HTTP tab.

### ISSUE THREAD

**Issue by siggihergeirs** [grafana/k6-cloud-feature-requests#45]
Would be convenient to have button to get a copy of the url shown test result  under http tab. (instead having to inspect the elemnt and grapping the url in dev tools)

**Comment by robingustafsson** [comment]
Thanks so much @siggihergeirs for the request. This will be fixed in an upcoming release (it's part of a larger set of changes to the result page that the team has been working on for some months). The release is currently planned for January, but might happen earlier. Will update here when it's out.

**Comment by robingustafsson** [comment]
This has now been shipped, and is available since yd. Hover a URL and there's a button in the tooltip:
<img width="595" alt="bild" src="https://user-images.githubusercontent.com/1792533/148976992-0c1f0927-55cc-487e-929d-27b6d8ac0674.png">
